services:
  web:
    build: .
    ports:
      - "3005:3000"
    volumes:
      - ./data1.csv:/usr/src/app/data1.csv:ro
      - ./data2.csv:/usr/src/app/data2.csv:ro
    environment:
      - NODE_ENV=production